// import {
//   ActionSheet,
//   Button,
//   Calendar,
//   Cell,
//   CellGroup,
//   Checkbox,
//   CheckboxGroup,
//   Col,
//   ContactCard,
//   ContactList,
//   DatetimePicker,
//   Dialog,
//   Divider,
//   DropdownItem,
//   DropdownMenu,
//   Empty,
//   Field,
//   Form,
//   Icon,
//   ImagePreview,
//   List,
//   NavBar,
//   Overlay,
//   Picker,
//   Popup,
//   PullRefresh,
//   Radio,
//   RadioGroup,
//   Row,
//   Search,
//   Switch,
//   Tag,
//   Tab,
//   Tabs,
//   Toast,
//   Uploader,
//   Swipe,
//   SwipeItem
// } from 'vant'
//
// export default function loadComponent(app: any) {
//   app
//     .use(Picker)
//     .use(Popup)
//     .use(Toast)
//     .use(Tab)
//     .use(Tabs)
//     .use(Overlay)
//     .use(ImagePreview)
//     .use(ActionSheet)
//     .use(Row)
//     .use(Col)
//     .use(RadioGroup)
//     .use(Radio)
//     .use(Cell)
//     .use(CellGroup)
//     .use(DatetimePicker)
//     .use(Checkbox)
//     .use(CheckboxGroup)
//     .use(DropdownMenu)
//     .use(DropdownItem)
//     .use(NavBar)
//     .use(Search)
//     .use(Field)
//     .use(List)
//     .use(PullRefresh)
//     .use(Dialog)
//     .use(Icon)
//     .use(Uploader)
//     .use(Button)
//     .use(ContactList)
//     .use(Divider)
//     .use(Calendar)
//     .use(Tag)
//     .use(Form)
//     .use(Empty)
//     .use(Switch)
//     .use(ContactCard)
//     .use(Swipe)
//     .use(SwipeItem)
// }
